### ISSUE TITLE
Guide is broken on Windows

### ISSUE THREAD

**Issue by maba72** [add-ons/plugin.video.tvvlaanderen#27]
Hi,
Seems like the integration with iptv manager is broken.

2020-12-16 13:38:18.338 T:24560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Invalid format string
                                            Traceback (most recent call last):
                                              File "C:\Users\maba\AppData\Roaming\Kodi\addons\plugin.video.tvvlaanderen\addon_entry.py", line 18, in <module>
                                                run(argv)
                                              File "C:\Users\maba\AppData\Roaming\Kodi\addons\plugin.video.tvvlaanderen\resources\lib\addon.py", line 133, in run
                                                routing.run(params)
                                              File "C:\Users\maba\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "C:\Users\maba\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "C:\Users\maba\AppData\Roaming\Kodi\addons\plugin.video.tvvlaanderen\resources\lib\addon.py", line 128, in iptv_epg
                                                IPTVManager(int(routing.args['port'][0])).send_epg()  # pylint: disable=too-many-function-args
                                              File "C:\Users\maba\AppData\Roaming\Kodi\addons\plugin.video.tvvlaanderen\resources\lib\modules\iptvmanager.py", line 41, in send
                                                sock.sendall(json.dumps(func(self)).encode())  # pylint: disable=not-callable
                                              File "C:\Users\maba\AppData\Roaming\Kodi\addons\plugin.video.tvvlaanderen\resources\lib\modules\iptvmanager.py", line 77, in send_epg
                                                for channel, programs in epg_api.get_guide_with_capi([channel.station_id for channel in channels], date).items():
                                              File "C:\Users\maba\AppData\Roaming\Kodi\addons\plugin.video.tvvlaanderen\resources\lib\solocoo\epg.py", line 125, in get_guide_with_capi
                                                'f': date_from.strftime("%s") + '000',  # from timestamp
                                            ValueError: Invalid format string
                                            -->End of Python script error report<--

**Comment by michaelarnauts** [comment]
Hmm, it seems datetime.strftime('%s') isn't supported on Windows. This needs to be fixed here.

**Comment by maba72** [comment]
Hi
Indeed, after modifying to %S all works fine :
![image](https://user-images.githubusercontent.com/47752020/102352920-b2197300-3fa8-11eb-8844-02adc49cdd64.png)

**Comment by michaelarnauts** [comment]
Hmm, that's strange, since `%S` will return the seconds from the date_from instead of the actual unix timestamp. Do you get correct guide data?

**Comment by maba72** [comment]
Hi Michael,
Absolutely right, the %S does not return the correct format, at  first the guide data seemed ok but I guess it was cached data.

**Comment by michaelarnauts** [comment]
@maba72 Can you try with one of those zips?

Leia: [plugin.video.tvvlaanderen-1.0.0-run-ci-on-windows-e27c09d.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/5709107/plugin.video.tvvlaanderen-1.0.0-run-ci-on-windows-e27c09d.zip)

Matrix: [plugin.video.tvvlaanderen-1.0.0+matrix.1-run-ci-on-windows-e27c09d.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/5709106/plugin.video.tvvlaanderen-1.0.0%2Bmatrix.1-run-ci-on-windows-e27c09d.zip)

**Comment by maba72** [comment]
works like a charm ! 
Thanks for the lightning fast action.

Greetings
Marc

**Comment by michaelarnauts** [comment]
@maba72 I've released version 1.0.1 that includes this fix. Thanks for reporting!
